### ISSUE TITLE
Unique key prop issue in Sidebar Component

### ISSUE THREAD

**Issue by Dorcastunmise** [Dorcastunmise/note-app#1] opened 2022-08-23 13:27 UTC
Key prop issue has led to element type being invalid.

**Comment by eldyl** [comment] 2022-08-23 19:43
I can take a look if you still need help. I'll fork your repo.

**Comment by eldyl** [comment] 2022-08-23 21:26
I am not seeing any errors as described. Generally, the issue sounds like it is related to mapping through an array, and then failing to give each item a unique index. I see you are giving an index to the each mapped `note` in your Sidebar component. The `note.id` sounds like the problem. I would look into how this property is being assigned to a new object.

One concept that I think is very relevant here is adding to the beginning of an array. When you add to the beginning of an array, the whole array must be re-indexed. This means if you are calling items by their original index later, you will receive the wrong item. In general, this could cause some issues. 

For example, on line 25 of your App component, you are adding to the beginning of an array. It looks like you are using this method to get the most recent entry to render on top, but this can cause issues, and could be relevant to the issue you are experiencing.

Feel free to elaborate further if you would like additional help.

**Comment by Dorcastunmise** [comment] 2022-08-24 16:56
Thank you so much. Now the thing is ..I don't know what else to do, where and how to make the changes.

**Comment by eldyl** [comment] 2022-08-24 17:00
Could you post a screenshot of the exact error message that you are experiencing?

**Comment by Dorcastunmise** [comment] 2022-08-24 17:05
![Screenshot (122)](https://user-images.githubusercontent.com/105108549/186479605-b29416bb-0de9-42c3-bcbc-b2ee9bf43208.png)

**Comment by Dorcastunmise** [comment] 2022-08-24 17:05
![Screenshot (117)](https://user-images.githubusercontent.com/105108549/186479659-9b92044c-bb59-4f51-b63f-a0b32adde786.png)

**Comment by GetUllrichorDieTrying** [comment] 2022-08-24 17:49
I think I know what the issue is. 

Look at how `data.js` is being exported.

https://stackoverflow.com/questions/44897070/element-type-is-invalid-expected-a-string-for-built-in-components-or-a-class

**Comment by Dorcastunmise** [comment] 2022-08-25 07:54
Tried merging....the console still responds with the last picture I sent. Thanks for helping by the way.

**Comment by eldyl** [comment] 2022-08-25 16:42
Happy to help. I am thinking the two issues in these screenshots may not have the same cause.

For the console log on your localhost (first screenshot), what steps are you completing to get the error message? When I boot up on my local machine, I am not receiving any errors. If I can get it to happen on my end, it will be easier to look into. I have tried editing notes, deleting, making new, etc.

I realized the second error is being received during deployment of the app. When I did some googling it looks like people receive the second error when experiencing a problem with import syntax. 

This thread has some more on it: https://stackoverflow.com/questions/44897070/element-type-is-invalid-expected-a-string-for-built-in-components-or-a-class.

**Comment by Dorcastunmise** [comment] 2022-08-25 18:59
Sorry sor the late response. The second error is the only one I've been experiencing.. 
I have gone through that thread before. I tried everything I could. Still had the issue.

**Comment by eldyl** [comment] 2022-08-25 20:49
React-mde (https://github.com/andrerpena/react-mde) seems to be the issue for the deployment. Version 11.5 is no longer maintained, and [others are experiencing the same issue](https://github.com/andrerpena/react-mde/issues/341).  React-mde requires `npm install react-mde --legacy-peer-deps`, which could likely be the issue for the deployment. 

I would consider a more well maintained markdown editor. This one might be worth a try: https://github.com/uiwjs/react-md-editor.

**Comment by Dorcastunmise** [comment] 2022-08-27 15:08
It's so paiful I'm just getting to see this. Thanks a lot. I'll work o ASAP

**Comment by Dorcastunmise** [comment] 2022-08-27 15:32
Guess what???
It's working!!!

**Comment by eldyl** [comment] 2022-08-27 18:15
Nice work! The deployment looks good!

**Closed as completed** 2022-08-30 18:03 UTC
Labels: help wanted, good first issue, question
